import blocksmith
import os
os.system("clear;sleep 2;echo -e '\e[1;33m\n\nBienvenido al script para minar btc a partir de keys privadas\nA continuación se empezará a generar Keys privadas a través de un algoritmo personalizado\e[0m'") 
os.system("sleep 6")
kg = blocksmith.KeyGenerator()
kg.seed_input('Generador de keys privadas btc')
key = kg.generate_key()
print("\n"+"KEY\n"+key)
os.system("sleep 2")
key2 = kg.generate_key()
print("\n"+"KEY\n"+key2)
os.system("sleep 2")
key3 = kg.generate_key()
print("\n"+"KEY\n"+key3)
os.system("sleep 2")
key4 = kg.generate_key()
print("\n"+"KEY\n"+key4)
os.system("sleep 2")
key5 = kg.generate_key()
print("\n"+"KEY\n"+key5) 
os.system("sleep 2")
key6 = kg.generate_key()
print("\n"+"KEY\n"+key6)
os.system("sleep 2")
key7 = kg.generate_key()
print("\n"+"KEY\n"+key7)
os.system("sleep 2")
key8 = kg.generate_key()
print("\n"+"KEY\n"+key8)
os.system("sleep 2")
key9 = kg.generate_key()
print("\n"+"KEY\n"+key9)
os.system("sleep 2")
key10 = kg.generate_key()
print("\n"+"\x1b[1;32m"+"KEY\n"+key10) 
os.system("sleep 2;echo -e '\e[1;33m\n\nIngrese a https://privatekeys.space/brainwallet para chackear las keys generadas\n\nGracias por utilizar mi script privado by VW\e[0m'")